kind: PersistentVolume
apiVersion: v1
metadata:
  name: clickhouse-pv-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/clickhouse_pv_0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ch-0-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
---